remove counter
golioth/zephyr-sdk pull request #120
Opened 2021-12-02 22:19 UTC by vancefarren

2021-12-02 22:23 UTC, 0Grit commented
I recall this discussion from our review. Can you summarize the context of it in a sentence or two in the PR description?

2021-12-07 09:48 UTC, mniestroj requested changes
> I recall this discussion from our review. Can you summarize the context of it in a sentence or two in the PR description?

The same should be done for commit message. There needs to be a reason for each change and this reason should always be mentioned in commit message. Having full context of each change inside git allows us to be independent of Github and allows to easily search through history of the repo, without entering Github UI.

See also: https://github.com/golioth/zephyr-sdk/blob/main/CONTRIBUTING.md#style--commit-guide

Commit title should be something like: `samples: lightdb_led: remove counter`. If in doubt, just look into previous commit messages in similar area / directory, e.g. with `git log --oneline -- samples/lightdb_led`.

The exact reason why `gitlint` job is failing right now is to prevent commiting patches that do not have proper commit body, i.e. description of why this change is desirable.

2021-12-07 10:19 UTC, 0Grit commented
> 
> See also: https://github.com/golioth/zephyr-sdk/blob/main/CONTRIBUTING.md#style--commit-guide
> 
> Commit title should be something like: `samples: lightdb_led: remove counter`. If in doubt, just look into previous commit messages in similar area / directory, e.g. with `git log --oneline -- samples/lightdb_led`.

MCU developers and hardware engineers like me will struggle with this. I want to maintain the rigor of Zephyr/Linux but will keep an eye out for a middle ground. 

Or at least look for ways to ease their/our transition into the civilized world.

2021-12-07 20:41 UTC, vitprajzler commented
I agree with Marcin's reasoning. Having the right level of context within the git scope (rather than being dependent on 3rd party tool) prevents problems when performing / reviewing git actions in the future.

It is something to get used to work-flow wise. But since we aim to contribute to Zephyr itself, the effort is well worth it. And our own repo is a good starting point for that (lower stakes than Zephyr contributions).

2021-12-10 15:16 UTC, 0Grit commented
@vancefarren Do you need to update any of the user facing docs as a result of this PR?

2021-12-10 15:17 UTC, 0Grit approved these changes

2021-12-10 20:05 UTC, merged

2021-12-10 20:05 UTC, vancefarren commented
> @vancefarren Do you need to update any of the user facing docs as a result of this PR?

I will look into it

2021-12-13 16:13 UTC, mniestroj commented
Commit author:
```
Author:     vancefarren <vancefarren@gmail.com>
```
Commit body:
```
...
Signed-off-by: Vance Farren <vance@golioth.io>

Co-authored-by: Vance Farren <vance@golioth.io>
```

Really? :)

2021-12-13 17:43 UTC, 0Grit commented
Could have swore we unified these before force push. Guess we got none of them.

> Commit author:
> 
> ```
> Author:     vancefarren <vancefarren@gmail.com>
> ```
> 
> Commit body:
> 
> ```
> ...
> Signed-off-by: Vance Farren <vance@golioth.io>
> 
> Co-authored-by: Vance Farren <vance@golioth.io>
> ```
> 
> Really? :)